<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gistFileName</name>
   <tag></tag>
   <elementGuidId>741402fe-114a-4bc2-a4e3-44fd74d49e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.user-select-contain</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
