<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCreatePublic</name>
   <tag></tag>
   <elementGuidId>5ecd9afa-899e-4732-a79c-e0d4e5f22419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hx_create-pr-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
