<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSelectMenu</name>
   <tag></tag>
   <elementGuidId>5df3ae29-031e-4588-9af2-5bc1ecb83337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.select-menu-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
