<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gistCode</name>
   <tag></tag>
   <elementGuidId>f5659981-103b-40cd-91e5-20ed8a21afe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.CodeMirror-line</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
